name = "my-project"
compatibility_date = "2025-01-14"
compatibility_flags = ["nodejs_compat"]

# Required for Cloudflare Pages - must match the adapter config
pages_build_output_dir = "build"

[build]
command = "npm run build"
